language: c

jobs:
  include:
    - name: "Linux"
      os: linux
      dist: bionic
      script:
        - make
        - make CC=clang
    - name: "macOS"
      os: osx
      osx_image: xcode11.2
      before_install:
        - brew install gcc
      script:
        - make CC=gcc-9
        - make CC=clang
    - name: "Windows"
      os: windows
      script:
        - mingw32-make CC=cl
