language: c

git:
  depth: false
  
jobs:
  include:
    - name: "Linux"
      os: linux
      dist: bionic
      script:
        - make
        - make CC=clang
    - name: "macOS"
      os: osx
      osx_image: xcode11.2
      before_install:
        - brew install gcc
      script:
        - make CC=gcc-9
        - make CC=clang
    - name: "Windows"
      os: windows
      script:
        - powershell -NoProfile -Command 'mingw32-make CC=C:\Program\\` Files\\` \\`(x86\\`)\Microsoft\\` Visual\\` Studio\2017\BuildTools\VC\Tools\MSVC\15.8.9.0\bin\Hostx86\x64\cl.exe'
