language: c

jobs:
  include:
    - name: "Linux"
      os: linux
      dist: bionic
    - name: "macOS"
      os: osx
      osx_image: xcode11.2
    - name: "Windows"
      os: windows
      before_install:
        - choco install -y llvm
        - choco install -y make

script:
  - make
  - make CC=clang