image: Visual Studio 2019

build: off

install:
- cinst make

test_script:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- mingw32-make CC=cl.exe