image:
- Visual Studio 2017
- Ubuntu
- macOS

build: off

install:
- cmd: cinst make
- sh: if [ true = "$CI_LINUX" ]; then sudo apt update; fi
- sh: if [ true = "$CI_LINUX" ]; then sudo apt install -y clang valgrind; fi

test_script:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- cmd: make test CC=cl.exe
- sh: if [ true = "$CI_LINUX" ]; then make test; fi
- sh: if [ true = "$CI_LINUX" ]; then valgrind ./test_boolean; fi
- sh: if [ true = "$CI_LINUX" ]; then valgrind ./test_integer; fi
- sh: if [ true = "$CI_LINUX" ]; then valgrind ./test_cmath; fi
- sh: if [ true = "$CI_LINUX" ]; then valgrind ./test_cstring; fi
- sh: if [ true = "$CI_LINUX" ]; then valgrind ./test_term_color; fi
- sh: if [ true = "$CI_LINUX" ]; then make clean; fi
- sh: make CC=gcc
- sh: make CC=clang
