image:
- Visual Studio 2017
- Ubuntu
- macOS

build: off

install:
- cmd: cinst make

test_script:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- cmd: make test CC=cl.exe
- sh: make